name: First Workflow

# The event/s that triggers the workflow
on:
  push:
    branches:
     - action-test

# Jobs to run
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get IP
        run: ip addr | grep "inet "